# Generated by Django 5.0 on 2023-12-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='p_email',
        ),
    ]
